### PR TITLE
Fixes #23

### LINKED ISSUE #23: glutexample.nim not working on osx.
Compiles fine, when trying to run:

``` console
glut_example(30911,0x7fff72619300) malloc: *** mach_vm_map(size=18446744070157651968) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
2015-04-23 16:37:03.961 glut_example[30911:7765855] GLUT Fatal Error: out of memory.
```

Tried a hello world glut app in cpp, it works.

### PR DESCRIPTION
**Pull request by ForsakenHarmony**

### CODE REVIEW

File: examples/glut_example.nim [hunk 1]
```diff
@@ -88,7 +88,8 @@ proc reshape(width: GLsizei, height: GLsizei) {.cdecl.} =
   # Enable perspective projection with fovy, aspect, zNear and zFar
   gluPerspective(45.0, width / height, 0.1, 100.0)
 
-glutInit()
+var x: cint = 0
```
Comment (dom96) [inline examples/glut_example.nim]: thank you for creating this, but seeing as this is an example let's make it more readable. Rename this to ``argc``.

Comment (ForsakenHarmony) [inline examples/glut_example.nim]: done
